export type CodiconName =
  | 'chevron-down'
  | 'chevron-right'
  | 'collapse-all'
  | 'expand-all'
  | 'code'
  | 'file'
  | 'folder'
  | 'folder-opened'
  | 'layout-sidebar-left'
  | 'layout-sidebar-left-off'
  | 'link-external'
  | 'loading'
  | 'open-preview'
  | 'refresh'
  | 'save'
  | 'trash'
